@extends('layouts.page')
@push('css')
    <link href="{{ asset('css/home/season/season.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
@endpush
@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js" defer></script>
    <script src="{{ asset('js/home/season/season.js') }}" defer></script>

@endpush
@section('content')
    <section class="season">
    <div class="container">
        <div class="row">
            <div class="col-12 page-title-wrapper">
                <h1 class="page-title">Sezon 2019/2020</h1>
                <div>
                    <select class="selectpicker">
                        <option value="league-1" selected>I Liga</option>
                        <option value="league-2">II Liga</option>
                        <option value="league-3">III Liga</option>
                        <option value="league-4">IV Liga</option>
                        <option value="league-5">V Liga</option>
                        <option value="league-6">Liga Kobiet</option>
                    </select>
                </div>
            </div>
            <div class="col-12">
                <table class="table" id="league-1" >
                            <thead>
                                <th>#</th>
                                <th>Drużyna</th>
                                <th>L.M.</th>
                                <th>L.P.</th>
                                <th>W.</th>
                                <th>P.</th>
                                <th>S.W.</th>
                                <th>S.P.</th>
                                <th>+/-</th>
                            </thead>
                            <tr>
                                <td>
                                    1
                                </td>
                                <td style="font-weight: 600">
                                    Apollo
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>23</b>
                                </td>
                                <td>
                                    <b>8</b>
                                </td>
                                <td>
                                    <b>1</b>
                                </td>
                                <td>
                                    <b>17</b>
                                </td>
                                <td>
                                    <b>4</b>
                                </td>
                                <td>
                                    <b>+52</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2
                                </td>
                                <td style="font-weight: 600">
                                    Absolwenci
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>20</b>
                                </td>
                                <td>
                                    <b>7</b>
                                </td>
                                <td>
                                    <b>2</b>
                                </td>
                                <td>
                                    <b>15</b>
                                </td>
                                <td>
                                    <b>6</b>
                                </td>
                                <td>
                                    <b>+50</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3
                                </td>
                                <td style="font-weight: 600">
                                    Lotnicy
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>17</b>
                                </td>
                                <td>
                                    <b>6</b>
                                </td>
                                <td>
                                    <b>3</b>
                                </td>
                                <td>
                                    <b>13</b>
                                </td>
                                <td>
                                    <b>8</b>
                                </td>
                                <td>
                                    <b>+30</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4
                                </td>
                                <td style="font-weight: 600">
                                    AS Gwoździe
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>16</b>
                                </td>
                                <td>
                                    <b>5</b>
                                </td>
                                <td>
                                    <b>4</b>
                                </td>
                                <td>
                                    <b>12</b>
                                </td>
                                <td>
                                    <b>8</b>
                                </td>
                                <td>
                                    <b>+9</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5
                                </td>
                                <td style="font-weight: 600">
                                    Ars Medica
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>15</b>
                                </td>
                                <td>
                                    <b>5</b>
                                </td>
                                <td>
                                    <b>4</b>
                                </td>
                                <td>
                                    <b>12</b>
                                </td>
                                <td>
                                    <b>10</b>
                                </td>
                                <td>
                                    <b>+6</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    6
                                </td>
                                <td style="font-weight: 600">
                                    Globtroter
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>12</b>
                                </td>
                                <td>
                                    <b>4</b>
                                </td>
                                <td>
                                    <b>5</b>
                                </td>
                                <td>
                                    <b>10</b>
                                </td>
                                <td>
                                    <b>13</b>
                                </td>
                                <td>
                                    <b>-11</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7
                                </td>
                                <td style="font-weight: 600">
                                    Mordeczki
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>11</b>
                                </td>
                                <td>
                                    <b>4</b>
                                </td>
                                <td>
                                    <b>5</b>
                                </td>
                                <td>
                                    <b>9</b>
                                </td>
                                <td>
                                    <b>12</b>
                                </td>
                                <td>
                                    <b>-11</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    8
                                </td>
                                <td style="font-weight: 600">
                                    Silver Town
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>8</b>
                                </td>
                                <td>
                                    <b>3</b>
                                </td>
                                <td>
                                    <b>6</b>
                                </td>
                                <td>
                                    <b>7</b>
                                </td>
                                <td>
                                    <b>14</b>
                                </td>
                                <td>
                                    <b>-46</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9
                                </td>
                                <td style="font-weight: 600">
                                    SKP Bartosz
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>8</b>
                                </td>
                                <td>
                                    <b>3</b>
                                </td>
                                <td>
                                    <b>6</b>
                                </td>
                                <td>
                                    <b>7</b>
                                </td>
                                <td>
                                    <b>15</b>
                                </td>
                                <td>
                                    <b>-33</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10
                                </td>
                                <td style="font-weight: 600">
                                    Wifra
                                </td>
                                <td>
                                    9
                                </td>
                                <td>
                                    <b>5</b>
                                </td>
                                <td>
                                    <b>2</b>
                                </td>
                                <td>
                                    <b>8</b>
                                </td>
                                <td>
                                    <b>4</b>
                                </td>
                                <td>
                                    <b>16</b>
                                </td>
                                <td>
                                    <b>-46</b>
                                </td>
                            </tr>
                        </table>
                <table class="table" id="league-2" style="display: none">
                    <thead>
                    <th>#</th>
                    <th>Drużyna</th>
                    <th>L.M.</th>
                    <th>L.P.</th>
                    <th>W.</th>
                    <th>P.</th>
                    <th>S.W.</th>
                    <th>S.P.</th>
                    <th>+/-</th>
                    </thead>
                    <tr>
                        <td>
                            1
                        </td>
                        <td style="font-weight: 600">
                            AKKS Husaria
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>24</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>17</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>+114</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            2
                        </td>
                        <td style="font-weight: 600">
                            Hilcus Olkusz
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>21</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>15</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>+43</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            3
                        </td>
                        <td style="font-weight: 600">
                            Whatever
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>17</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>+20</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            4
                        </td>
                        <td style="font-weight: 600">
                            Appel
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>15</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>+16</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            5
                        </td>
                        <td style="font-weight: 600">
                            GeoVolley Team
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>10</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>-16</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            6
                        </td>
                        <td style="font-weight: 600">
                            SA PSP
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>12</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>10</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>+9</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            7
                        </td>
                        <td style="font-weight: 600">
                            XII
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>12</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>-18</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            8
                        </td>
                        <td style="font-weight: 600">
                            Korpusiki
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>-42</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            9
                        </td>
                        <td style="font-weight: 600">
                            Pradmix
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>16</b>
                        </td>
                        <td>
                            <b>-68</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            10
                        </td>
                        <td style="font-weight: 600">
                            TKKF Jura
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>16</b>
                        </td>
                        <td>
                            <b>-58</b>
                        </td>
                    </tr>
                </table>
                <table class="table" id="league-3" style="display: none">
                    <thead>
                    <th>#</th>
                    <th>Drużyna</th>
                    <th>L.M.</th>
                    <th>L.P.</th>
                    <th>W.</th>
                    <th>P.</th>
                    <th>S.W.</th>
                    <th>S.P.</th>
                    <th>+/-</th>
                    </thead>
                    <tr>
                        <td>
                            1
                        </td>
                        <td style="font-weight: 600">
                            Turbo - AZS UP Kraków
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>20</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>+47</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            2
                        </td>
                        <td style="font-weight: 600">
                            EVT
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>18</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>+78</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            3
                        </td>
                        <td style="font-weight: 600">
                            Victoria Dłużec
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>10</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>+11</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            4
                        </td>
                        <td style="font-weight: 600">
                            Amplus
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>44</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>10</b>
                        </td>
                        <td>
                            <b>+1</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            5
                        </td>
                        <td style="font-weight: 600">
                            Promil
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>-11</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            6
                        </td>
                        <td style="font-weight: 600">
                            Dzikie Klocki - Bakcyl
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>10</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>10</b>
                        </td>
                        <td>
                            <b>-5</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            7
                        </td>
                        <td style="font-weight: 600">
                            VC Rozrywka
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>-16</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            8
                        </td>
                        <td style="font-weight: 600">
                            Recco Kraków
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>-40</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            9
                        </td>
                        <td style="font-weight: 600">
                            Gwozdzie
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>-65</b>
                        </td>
                    </tr>
                </table>
                <table class="table" id="league-4" style="display: none">
                    <thead>
                    <th>#</th>
                    <th>Drużyna</th>
                    <th>L.M.</th>
                    <th>L.P.</th>
                    <th>W.</th>
                    <th>P.</th>
                    <th>S.W.</th>
                    <th>S.P.</th>
                    <th>+/-</th>
                    </thead>
                    <tr>
                        <td>
                            1
                        </td>
                        <td style="font-weight: 600">
                            MKS Tytan
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>19</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>+54</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            2
                        </td>
                        <td style="font-weight: 600">
                            AK 47
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>15</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>12</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>+42</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            3
                        </td>
                        <td style="font-weight: 600">
                            KKS Atak
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>+23</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            4
                        </td>
                        <td style="font-weight: 600">
                            Instytut Geografii UP
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>12</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>12</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>+1</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            5
                        </td>
                        <td style="font-weight: 600">
                            Pickles
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>12</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>+7</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            6
                        </td>
                        <td style="font-weight: 600">
                            Porażka
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>-27</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            7
                        </td>
                        <td style="font-weight: 600">
                            TKKF Energia
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>10</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>-24</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            8
                        </td>
                        <td style="font-weight: 600">
                            Netmix
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>-31</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            9
                        </td>
                        <td style="font-weight: 600">
                            Kretes
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>-45</b>
                        </td>
                    </tr>
                </table>
                <table class="table" id="league-5" style="display: none">
                    <thead>
                    <th>#</th>
                    <th>Drużyna</th>
                    <th>L.M.</th>
                    <th>L.P.</th>
                    <th>W.</th>
                    <th>P.</th>
                    <th>S.W.</th>
                    <th>S.P.</th>
                    <th>+/-</th>
                    </thead>
                    <tr>
                        <td>
                            1
                        </td>
                        <td style="font-weight: 600">
                            Srednia Wieku
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>22</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>17</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>+105</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            2
                        </td>
                        <td style="font-weight: 600">
                            Wataha Yorków
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>22</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>17</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>+94</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            3
                        </td>
                        <td style="font-weight: 600">
                            Wczorajsi
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>21</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>15</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>+45</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            4
                        </td>
                        <td style="font-weight: 600">
                            Hefalumpy
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>16</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>+70</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            5
                        </td>
                        <td style="font-weight: 600">
                            LWWL
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>15</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>10</b>
                        </td>
                        <td>
                            <b>+54</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            6
                        </td>
                        <td style="font-weight: 600">
                            Wybrzeże Klatki Schodowej
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>15</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>-11</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            7
                        </td>
                        <td style="font-weight: 600">
                            Quick
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>15</b>
                        </td>
                        <td>
                            <b>-23</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            8
                        </td>
                        <td style="font-weight: 600">
                            Iskra Pałecznica
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>-91</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            9
                        </td>
                        <td style="font-weight: 600">
                            Biesiatnicy
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>17</b>
                        </td>
                        <td>
                            <b>-107</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            10
                        </td>
                        <td style="font-weight: 600">
                            Alfa i Omega
                        </td>
                        <td>
                            9
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>16</b>
                        </td>
                        <td>
                            <b>-136</b>
                        </td>
                    </tr>
                </table>
                <table class="table" id="league-6" style="display: none">
                    <thead>
                    <th>#</th>
                    <th>Drużyna</th>
                    <th>L.M.</th>
                    <th>L.P.</th>
                    <th>W.</th>
                    <th>P.</th>
                    <th>S.W.</th>
                    <th>S.P.</th>
                    <th>+/-</th>
                    </thead>
                    <tr>
                        <td>
                            1
                        </td>
                        <td style="font-weight: 600">
                            TKKF Stars
                        </td>
                        <td>
                            7
                        </td>
                        <td>
                            <b>19</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>0</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>+115</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            2
                        </td>
                        <td style="font-weight: 600">
                            KS Bronowianka 2
                        </td>
                        <td>
                            7
                        </td>
                        <td>
                            <b>17</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>12</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>+69</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            3
                        </td>
                        <td style="font-weight: 600">
                            Sunrise
                        </td>
                        <td>
                            7
                        </td>
                        <td>
                            <b>15</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>11</b>
                        </td>
                        <td>
                            <b>5</b>
                        </td>
                        <td>
                            <b>+52</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            4
                        </td>
                        <td style="font-weight: 600">
                            Pradniczanka 2
                        </td>
                        <td>
                            7
                        </td>
                        <td>
                            <b>13</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>+9</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            5
                        </td>
                        <td style="font-weight: 600">
                            MOS Kraków Zachód 3D Sport
                        </td>
                        <td>
                            7
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>+9</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            6
                        </td>
                        <td style="font-weight: 600">
                            Salos Kraków RP
                        </td>
                        <td>
                            7
                        </td>
                        <td>
                            <b>8</b>
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>4</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>9</b>
                        </td>
                        <td>
                            <b>-42</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            7
                        </td>
                        <td style="font-weight: 600">
                            Atomówki
                        </td>
                        <td>
                            7
                        </td>
                        <td>
                            <b>3</b>
                        </td>
                        <td>
                            <b>1</b>
                        </td>
                        <td>
                            <b>6</b>
                        </td>
                        <td>
                            <b>2</b>
                        </td>
                        <td>
                            <b>12</b>
                        </td>
                        <td>
                            <b>-76</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            8
                        </td>
                        <td style="font-weight: 600">
                            Netmix
                        </td>
                        <td>
                            7
                        </td>
                        <td>
                            <b>0</b>
                        </td>
                        <td>
                            <b>0</b>
                        </td>
                        <td>
                            <b>7</b>
                        </td>
                        <td>
                            <b>0</b>
                        </td>
                        <td>
                            <b>14</b>
                        </td>
                        <td>
                            <b>-136</b>
                        </td>
                    </tr>

                </table>

            </div>
        </div>
    </div>
    </section>
@endsection
